service: tacoRecipeService

package:
  individually: true

plugins:
  # - serverless-plugin-typescript
  # - serverless-webpack
  - ${file(./serverless.plugin.js):usePlugin} # TODO only allows js files, file issue for .cjs
  - serverless-offline

# https://www.serverless.com/framework/docs/deprecations/#new-variables-resolver
variablesResolutionMode: 20210326

provider:
  # apiGateway:
  #   binaryMediaTypes:
  #     - '*/*'
  # https://www.serverless.com/framework/docs/deprecations/#default-providerlambdahashingversion
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  memorySize: 512

functions:
  - ${file(./functions/createTacoRecipe/serverless.yml)}
  - ${file(./functions/deleteTacoRecipe/serverless.yml)}
  - ${file(./functions/getTacoRecipes/serverless.yml)}
  - ${file(./functions/getTacoSauces/serverless.yml)}
  - ${file(./functions/postTacoRecipeCard/serverless.yml)}
  - ${file(./functions/updateTacoRecipe/serverless.yml)}

custom:
  webpack:
    webpackConfig: webpack.config.cjs # file issue, .cjs should work automatically!
