/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  readonly "/recipe/taco": {
    readonly post: {
      readonly responses: {
        readonly 200: {
          readonly content: {
            readonly "application/json": {
              readonly id: string;
              readonly message: string;
            };
          };
        };
      };
      readonly requestBody: {
        readonly content: {
          readonly "application/json": {
            readonly description: string;
            readonly ingredients: {
              readonly shell: string;
              readonly proteins: readonly string[];
              readonly toppings: readonly string[];
              readonly sauces?: readonly string[];
            };
            readonly instructions: string;
            readonly name: string;
          };
        };
      };
    };
  };
}

export interface components {}

export interface operations {}

export interface external {}
